version = "1.0"

[metadata]
author_name = "Steve Jobs"
author_email = "steve@apple.com"
difficulty = "easy"
category = "programming"
tags = ["trivial"]

[verifier]

[agent]
env = {ANTHRPIC_API_KEY= "REDACTED" }

[solution]


[[environment.mcp_servers]]
name = "mcp-server"
transport = "streamable-http"
url = "http://mcp-server:8000/mcp"
